// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU3Ut5RsbJwHw2OIEu-AoHbRvrAzzFHZI',
    appId: '1:174978620099:web:6ea64114cd0d604776a076',
    messagingSenderId: '174978620099',
    projectId: 'saotp-dbb0b',
    authDomain: 'saotp-dbb0b.firebaseapp.com',
    storageBucket: 'saotp-dbb0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo7Z6q3DRqT-axaV4p4Jq6u83eKiL_2_M',
    appId: '1:174978620099:android:bbff328b0a2039dc76a076',
    messagingSenderId: '174978620099',
    projectId: 'saotp-dbb0b',
    storageBucket: 'saotp-dbb0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0A4Rx5MdsR1WTKtrer0YDi21koYd_OhU',
    appId: '1:174978620099:ios:66a45b2ab0683ee476a076',
    messagingSenderId: '174978620099',
    projectId: 'saotp-dbb0b',
    storageBucket: 'saotp-dbb0b.appspot.com',
    iosBundleId: 'com.example.schedularApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0A4Rx5MdsR1WTKtrer0YDi21koYd_OhU',
    appId: '1:174978620099:ios:66a45b2ab0683ee476a076',
    messagingSenderId: '174978620099',
    projectId: 'saotp-dbb0b',
    storageBucket: 'saotp-dbb0b.appspot.com',
    iosBundleId: 'com.example.schedularApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU3Ut5RsbJwHw2OIEu-AoHbRvrAzzFHZI',
    appId: '1:174978620099:web:3aa5931ef0f6c28876a076',
    messagingSenderId: '174978620099',
    projectId: 'saotp-dbb0b',
    authDomain: 'saotp-dbb0b.firebaseapp.com',
    storageBucket: 'saotp-dbb0b.appspot.com',
  );
}
